import React from 'react';

const Disclaimer: React.FC = () => {
    return (
        <div className="bg-cyan-100 border-l-4 border-cyan-500 text-cyan-800 p-4 rounded-md shadow-sm" role="alert">
            <div className="flex">
                <div className="py-1">
                    <svg className="fill-current h-6 w-6 text-cyan-500 mr-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path d="M2.93 17.07A10 10 0 1 1 17.07 2.93 10 10 0 0 1 2.93 17.07zM9 5v6h2V5H9zm0 8h2v-2H9v2z"/></svg>
                </div>
                <div>
                    <p className="font-bold">For Informational Purposes Only</p>
                    <p className="text-sm">The advice generated by this AI tool is not a substitute for professional medical consultation. Please consult a healthcare provider for any health concerns.</p>
                </div>
            </div>
        </div>
    );
};

export default Disclaimer;